repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml

-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: ruff
        language: python
        types: [python]
        args: [check, --fix, --unsafe-fixes, bubble_parser]
