services:
  parser:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16.3

    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    restart: on-failure

    ports:
      - "5432:5432"

    volumes:
      - ./docker/postgres/volume:/var/lib/postgresql/data
