services:
  parser:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: on-failure
    working_dir: /app
    environment:
      - POSTGRES_HOST=postgres
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16.3

    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    restart: on-failure

    ports:
      - "5432:5432"

    volumes:
      - ./docker/postgres/volume:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 60s
      retries: 5
